name: Test

permissions:
  contents: write

on:
  push:
  pull_request:

# env:
#   CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  rust-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: string
        uses: ./
        with:
          url: https://github.com/denoland/deno
      - name: 1 string[]
        uses: ./
        with:
          url:  |-
           aa
           bb
           cc
      - name: 2 string[]
        uses: ./
        with:
          url: ["b", "a"]

      - name: 3 string[]
        uses: ./
        with:
          url:
            - a
            - b
